apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworldjava-controller
spec:
  replicas: 3
  selector:
    app: helloworldjava
  template:
    metadata:
      labels:
        app: helloworldjava
    spec:
      containers:
      - name: mavenrepo
        image: sunil752021/mavenrepo
        ports:
        - name: java-port
          containerPort: 3001
